/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a complaint */
        post: operations["createComplaint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an entity */
        post: operations["createEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search entities by name (fuzzy)
         * @description Trigram fuzzy search; returns up to 10 matches ordered by similarity.
         */
        get: operations["searchEntities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{id}/complaints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List complaints for an entity
         * @description Returns the top 20 complaints for the entity, most corroborated first, then newest.
         */
        get: operations["listComplaints"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/complaints/{id}/corroborate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Corroborate (endorse) a complaint
         * @description A user may corroborate a given complaint only once.
         */
        post: operations["corroborateComplaint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get a presigned S3 upload URL
         * @description Returns a short-lived (60s) presigned PUT URL plus the final public media URL.
         *     PUT the file to `uploadUrl` with a matching `Content-Type`, then send `mediaUrl`
         *     as the complaint's `mediaUrl`.
         */
        post: operations["generateUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global ranked feed
         * @description Complaints across all entities, ranked by a time-decay relevance score
         *     (corroborations vs. age). Page size is fixed at 10.
         */
        get: operations["getFeed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Human-readable error message (Portuguese). */
            error: string;
        };
        MessageResponse: {
            message: string;
        };
        /**
         * @description Kind of entity. Input is case-insensitive; stored/returned uppercase.
         * @enum {string}
         */
        EntityType: "PLACE" | "MOVIE" | "COMPANY" | "PRODUCT";
        Author: {
            /** Format: uuid */
            id: string;
            username: string;
        };
        CreateEntityInput: {
            name: string;
            type: components["schemas"]["EntityType"];
        };
        Entity: {
            /** Format: uuid */
            id: string;
            type: components["schemas"]["EntityType"];
            name: string;
            /**
             * Format: uuid
             * @description User id of the creator; null if unknown.
             */
            createdBy: string | null;
        };
        EntitySearchResult: {
            /** Format: uuid */
            id: string;
            name: string;
            type: components["schemas"]["EntityType"];
        };
        CreateComplaintInput: {
            /** Format: uuid */
            entityId: string;
            title: string;
            content: string;
            /** @description Optional. The `mediaUrl` returned by /uploads/presigned-url. */
            mediaUrl?: string | null;
        };
        Complaint: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            entityId: string;
            /** Format: uuid */
            authorId: string;
            title: string;
            content: string;
            mediaUrl: string | null;
            corroborationCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        ComplaintListItem: {
            /** Format: uuid */
            id: string;
            title: string;
            content: string;
            mediaUrl: string | null;
            corroborationCount: number;
            /** Format: date-time */
            createdAt: string;
            author: components["schemas"]["Author"];
        };
        FeedItem: {
            /** Format: uuid */
            id: string;
            title: string;
            content: string;
            mediaUrl: string | null;
            corroborationCount: number;
            /** Format: date-time */
            createdAt: string;
            author: components["schemas"]["Author"];
            entity: {
                /** Format: uuid */
                id: string;
                name: string;
            };
        };
        FeedResponse: {
            data: components["schemas"]["FeedItem"][];
            metadata: {
                currentPage: number;
                hasMore: boolean;
                nextPage: number | null;
            };
        };
        PresignedUrlInput: {
            /** @enum {string} */
            contentType: "image/jpeg" | "image/png" | "image/webp";
        };
        PresignedUrlResponse: {
            /**
             * Format: uri
             * @description Presigned S3 PUT URL, valid for 60 seconds.
             */
            uploadUrl: string;
            /**
             * Format: uri
             * @description Final public URL to store as the complaint's mediaUrl.
             */
            mediaUrl: string;
        };
    };
    responses: {
        /** @description Invalid or missing input. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Unexpected server error. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createComplaint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateComplaintInput"];
            };
        };
        responses: {
            /** @description Complaint created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Complaint"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    createEntity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityInput"];
            };
        };
        responses: {
            /** @description Entity created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    searchEntities: {
        parameters: {
            query: {
                /** @description Search term, minimum 2 characters. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching entities (max 10) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntitySearchResult"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    listComplaints: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Entity id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Complaints for the entity (max 20) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintListItem"][];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    corroborateComplaint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Complaint id. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Corroboration recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /** @description The user has already corroborated this complaint. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
    generateUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUrlInput"];
            };
        };
        responses: {
            /** @description Presigned upload URL issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            500: components["responses"]["InternalError"];
        };
    };
    getFeed: {
        parameters: {
            query?: {
                /** @description 1-based page number. Defaults to 1. */
                page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A page of feed items */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedResponse"];
                };
            };
            500: components["responses"]["InternalError"];
        };
    };
}
